### ISSUE TITLE
Wizard of Oz Title misspelled

### ISSUE THREAD

**Issue by Fazented** [rollestoncollege/webv4#14]
The title in the Wizard of Oz video is misspelled, as seen below. 

![image](https://github.com/rollestoncollege/webv4/assets/100059469/bae379b4-15fe-43fc-851d-e8b7ca334e84)

It should be **"Rolleston College Presents: The Wizard of Oz"** but **Presents** was spelled as **Persents**

**Comment by Husky-Devel** [comment]
Well too bad
