### ISSUE TITLE
Add more videos to showcase

### ISSUE THREAD

**Issue by Fazented** [rollestoncollege/webv4#17]
Rolleston College X-Factor and Rolleston College Haka are stated at the top of the page, but the videos are not linked in the showcase

**Comment by Husky-Devel** [comment]
Working on it

**Comment by Husky-Devel** [comment]
okdsjopsijdseiojfpoIDSjf

TYES FINN

**Comment by Husky-Devel** [comment]
YOUR BEAING WATCHED

**Comment by Fazented** [comment]
yeah i was watching you
